version: '3.7'
services:
  test: &base
    image: wrasilva/territory
    build: .
    volumes:
      - .:/usr/local/src
    depends_on:
      - postgres
    command: bundle exec rspec
    environment:
      - RAILS_ENV=test
  web:
    <<: *base
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    environment:
      - RAILS_ENV=development
    ports:
      - 3000:3000
  postgres:
    image: postgres
